[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "55c01f43d1e31a0ba8f4ddb00512f852d6dd09ba"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[MPICH.download]]
    sha256 = "934d8fcefde9152f69a9c6f973e95ac0daab18adc7235f170f5939f27fc82a40"
    url = "https://github.com/giordano/MPICH_debug_ch4_jll.jl/releases/download/MPICH-v4.1.0+2/MPICH.v4.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[MPICH]]
arch = "x86_64"
git-tree-sha1 = "3a9f9de945b2313789771ff5a4c1843a20233e22"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[MPICH.download]]
    sha256 = "6fa401ae3303c9edb3af9385e55fedd7059aa7d4b45fefa947880d51fe34bb2d"
    url = "https://github.com/giordano/MPICH_debug_ch4_jll.jl/releases/download/MPICH-v4.1.0+2/MPICH.v4.1.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
